using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using Avara.Exceptions;

namespace Avara.Models;

/// <summary>
/// A user's clinical or organizational role within the clinic.
/// </summary>
[JsonConverter(typeof(ClinicRoleConverter))]
public enum ClinicRole
{
    Doctor,
    Physician,
    Surgeon,
    Radiologist,
    Cardiologist,
    Neurologist,
    Urologist,
    Gynecologist,
    Endocrinologist,
    Oncologist,
    RadiationOncologist,
    Hematologist,
    Gastroenterologist,
    Pulmonologist,
    Nephrologist,
    Rheumatologist,
    Dermatologist,
    Ophthalmologist,
    Otolaryngologist,
    Pediatrician,
    Obstetrician,
    Psychiatrist,
    Anesthesiologist,
    EmergencyMedicinePhysician,
    FamilyMedicinePhysician,
    InternalMedicinePhysician,
    Pathologist,
    NuclearMedicinePhysician,
    PainManagementSpecialist,
    InfectiousDiseaseSpecialist,
    Immunologist,
    PhysicianAssistant,
    NursePractitioner,
    CertifiedRegisteredNurseAnesthetist,
    Psychologist,
    MedicalAssistant,
    Scribe,
    RegisteredNurse,
    NurseManager,
    PatientCareCoordinator,
    ImagingTechnologist,
    LaboratoryTechnician,
    MedicalLaboratoryScientist,
    PathologistsAssistant,
    Phlebotomist,
    Pharmacist,
    PharmacyTechnician,
    PhysicalTherapist,
    OccupationalTherapist,
    SpeechLanguagePathologist,
    RespiratoryTherapist,
    Nutritionist,
    FrontDeskOperator,
    RevenueCycleManager,
    AdministrativeDirector,
    AdministrativeAssistant,
    LegalAdministrator,
    ItAdministrator,
    ItSupport,
    SoftwareEngineer,
    Other,
}

sealed class ClinicRoleConverter : JsonConverter<ClinicRole>
{
    public override ClinicRole Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "Doctor" => ClinicRole.Doctor,
            "Physician" => ClinicRole.Physician,
            "Surgeon" => ClinicRole.Surgeon,
            "Radiologist" => ClinicRole.Radiologist,
            "Cardiologist" => ClinicRole.Cardiologist,
            "Neurologist" => ClinicRole.Neurologist,
            "Urologist" => ClinicRole.Urologist,
            "Gynecologist" => ClinicRole.Gynecologist,
            "Endocrinologist" => ClinicRole.Endocrinologist,
            "Oncologist" => ClinicRole.Oncologist,
            "Radiation Oncologist" => ClinicRole.RadiationOncologist,
            "Hematologist" => ClinicRole.Hematologist,
            "Gastroenterologist" => ClinicRole.Gastroenterologist,
            "Pulmonologist" => ClinicRole.Pulmonologist,
            "Nephrologist" => ClinicRole.Nephrologist,
            "Rheumatologist" => ClinicRole.Rheumatologist,
            "Dermatologist" => ClinicRole.Dermatologist,
            "Ophthalmologist" => ClinicRole.Ophthalmologist,
            "Otolaryngologist" => ClinicRole.Otolaryngologist,
            "Pediatrician" => ClinicRole.Pediatrician,
            "Obstetrician" => ClinicRole.Obstetrician,
            "Psychiatrist" => ClinicRole.Psychiatrist,
            "Anesthesiologist" => ClinicRole.Anesthesiologist,
            "Emergency Medicine Physician" => ClinicRole.EmergencyMedicinePhysician,
            "Family Medicine Physician" => ClinicRole.FamilyMedicinePhysician,
            "Internal Medicine Physician" => ClinicRole.InternalMedicinePhysician,
            "Pathologist" => ClinicRole.Pathologist,
            "Nuclear Medicine Physician" => ClinicRole.NuclearMedicinePhysician,
            "Pain Management Specialist" => ClinicRole.PainManagementSpecialist,
            "Infectious Disease Specialist" => ClinicRole.InfectiousDiseaseSpecialist,
            "Immunologist" => ClinicRole.Immunologist,
            "Physician Assistant" => ClinicRole.PhysicianAssistant,
            "Nurse Practitioner" => ClinicRole.NursePractitioner,
            "Certified Registered Nurse Anesthetist" =>
                ClinicRole.CertifiedRegisteredNurseAnesthetist,
            "Psychologist" => ClinicRole.Psychologist,
            "Medical Assistant" => ClinicRole.MedicalAssistant,
            "Scribe" => ClinicRole.Scribe,
            "Registered Nurse" => ClinicRole.RegisteredNurse,
            "Nurse Manager" => ClinicRole.NurseManager,
            "Patient Care Coordinator" => ClinicRole.PatientCareCoordinator,
            "Imaging Technologist" => ClinicRole.ImagingTechnologist,
            "Laboratory Technician" => ClinicRole.LaboratoryTechnician,
            "Medical Laboratory Scientist" => ClinicRole.MedicalLaboratoryScientist,
            "Pathologists' Assistant" => ClinicRole.PathologistsAssistant,
            "Phlebotomist" => ClinicRole.Phlebotomist,
            "Pharmacist" => ClinicRole.Pharmacist,
            "Pharmacy Technician" => ClinicRole.PharmacyTechnician,
            "Physical Therapist" => ClinicRole.PhysicalTherapist,
            "Occupational Therapist" => ClinicRole.OccupationalTherapist,
            "Speech-Language Pathologist" => ClinicRole.SpeechLanguagePathologist,
            "Respiratory Therapist" => ClinicRole.RespiratoryTherapist,
            "Nutritionist" => ClinicRole.Nutritionist,
            "Front Desk Operator" => ClinicRole.FrontDeskOperator,
            "Revenue Cycle Manager" => ClinicRole.RevenueCycleManager,
            "Administrative Director" => ClinicRole.AdministrativeDirector,
            "Administrative Assistant" => ClinicRole.AdministrativeAssistant,
            "Legal Administrator" => ClinicRole.LegalAdministrator,
            "IT Administrator" => ClinicRole.ItAdministrator,
            "IT Support" => ClinicRole.ItSupport,
            "Software Engineer" => ClinicRole.SoftwareEngineer,
            "Other" => ClinicRole.Other,
            _ => (ClinicRole)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        ClinicRole value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                ClinicRole.Doctor => "Doctor",
                ClinicRole.Physician => "Physician",
                ClinicRole.Surgeon => "Surgeon",
                ClinicRole.Radiologist => "Radiologist",
                ClinicRole.Cardiologist => "Cardiologist",
                ClinicRole.Neurologist => "Neurologist",
                ClinicRole.Urologist => "Urologist",
                ClinicRole.Gynecologist => "Gynecologist",
                ClinicRole.Endocrinologist => "Endocrinologist",
                ClinicRole.Oncologist => "Oncologist",
                ClinicRole.RadiationOncologist => "Radiation Oncologist",
                ClinicRole.Hematologist => "Hematologist",
                ClinicRole.Gastroenterologist => "Gastroenterologist",
                ClinicRole.Pulmonologist => "Pulmonologist",
                ClinicRole.Nephrologist => "Nephrologist",
                ClinicRole.Rheumatologist => "Rheumatologist",
                ClinicRole.Dermatologist => "Dermatologist",
                ClinicRole.Ophthalmologist => "Ophthalmologist",
                ClinicRole.Otolaryngologist => "Otolaryngologist",
                ClinicRole.Pediatrician => "Pediatrician",
                ClinicRole.Obstetrician => "Obstetrician",
                ClinicRole.Psychiatrist => "Psychiatrist",
                ClinicRole.Anesthesiologist => "Anesthesiologist",
                ClinicRole.EmergencyMedicinePhysician => "Emergency Medicine Physician",
                ClinicRole.FamilyMedicinePhysician => "Family Medicine Physician",
                ClinicRole.InternalMedicinePhysician => "Internal Medicine Physician",
                ClinicRole.Pathologist => "Pathologist",
                ClinicRole.NuclearMedicinePhysician => "Nuclear Medicine Physician",
                ClinicRole.PainManagementSpecialist => "Pain Management Specialist",
                ClinicRole.InfectiousDiseaseSpecialist => "Infectious Disease Specialist",
                ClinicRole.Immunologist => "Immunologist",
                ClinicRole.PhysicianAssistant => "Physician Assistant",
                ClinicRole.NursePractitioner => "Nurse Practitioner",
                ClinicRole.CertifiedRegisteredNurseAnesthetist =>
                    "Certified Registered Nurse Anesthetist",
                ClinicRole.Psychologist => "Psychologist",
                ClinicRole.MedicalAssistant => "Medical Assistant",
                ClinicRole.Scribe => "Scribe",
                ClinicRole.RegisteredNurse => "Registered Nurse",
                ClinicRole.NurseManager => "Nurse Manager",
                ClinicRole.PatientCareCoordinator => "Patient Care Coordinator",
                ClinicRole.ImagingTechnologist => "Imaging Technologist",
                ClinicRole.LaboratoryTechnician => "Laboratory Technician",
                ClinicRole.MedicalLaboratoryScientist => "Medical Laboratory Scientist",
                ClinicRole.PathologistsAssistant => "Pathologists' Assistant",
                ClinicRole.Phlebotomist => "Phlebotomist",
                ClinicRole.Pharmacist => "Pharmacist",
                ClinicRole.PharmacyTechnician => "Pharmacy Technician",
                ClinicRole.PhysicalTherapist => "Physical Therapist",
                ClinicRole.OccupationalTherapist => "Occupational Therapist",
                ClinicRole.SpeechLanguagePathologist => "Speech-Language Pathologist",
                ClinicRole.RespiratoryTherapist => "Respiratory Therapist",
                ClinicRole.Nutritionist => "Nutritionist",
                ClinicRole.FrontDeskOperator => "Front Desk Operator",
                ClinicRole.RevenueCycleManager => "Revenue Cycle Manager",
                ClinicRole.AdministrativeDirector => "Administrative Director",
                ClinicRole.AdministrativeAssistant => "Administrative Assistant",
                ClinicRole.LegalAdministrator => "Legal Administrator",
                ClinicRole.ItAdministrator => "IT Administrator",
                ClinicRole.ItSupport => "IT Support",
                ClinicRole.SoftwareEngineer => "Software Engineer",
                ClinicRole.Other => "Other",
                _ => throw new AvaraInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
